spring.application.name=Papeleria
server.port=9000

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/papeleria
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# (Opcional) Activar el Autocommit explicitamente en el pool
spring.datasource.hikari.auto-commit=true

# Numero maximo de conexiones simultaneas que el pool mantendra abiertas
spring.datasource.hikari.maximum-pool-size=20

# Numero minimo de conexiones inactivas que el pool mantendra listas
spring.datasource.hikari.minimum-idle=5

# Tiempo maximo (en milisegundos) que una peticion esperara por una conexion antes de lanzar un error
spring.datasource.hikari.connection-timeout=30000

# Tiempo maximo que una conexion puede estar inactiva en el pool antes de cerrarse
spring.datasource.hikari.idle-timeout=600000

# Tiempo maximo de vida de una conexion en el pool (evita fugas en la BD)
spring.datasource.hikari.max-lifetime=1800000

# Nombre asignado al pool para identificarlo facilmente en los logs de PostgreSQL
spring.datasource.hikari.pool-name=MiPostgresPool